### ISSUE TITLE
Advanced Engineering Practice 

### ISSUE THREAD

**Issue by kka-na** [inha-cvl/mobinha#56]
## TODO

- [ ] 사용자가 외부에서 사용할 어플리케이션만들기
- [ ] 외부에서 사용자 호출과 목적지 받아서 경로 생성하기
- [ ] 목적지까지 주행 후 사용자 종료 받고 주행 종료하기 
- [ ] 모라이로 테스트
